version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "8080:80"
    networks:
      - internal
  php:
    image: php:fpm-alpine
    volumes:
      - ./code:/var/www/html/
    networks:
      - internal
networks:
  internal:
    driver: bridge